apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-{{APP_ENV}}
  namespace: {{APP_ENV}}
  labels:
    app: worker-app-{{APP_ENV}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-app-{{APP_ENV}}
  template:
    metadata:
      labels:
        app: worker-app-{{APP_ENV}}
    spec:
      containers:
        - name: worker-app-{{APP_ENV}}
          image: {{WORKER_IMAGE}}
